# Generated by Django 3.0.7 on 2020-06-26 10:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humidityreading',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 6, 26, 10, 8, 39, 105459, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='temperaturereading',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 6, 26, 10, 8, 39, 105011, tzinfo=utc)),
        ),
    ]
