# Generated by Django 3.0.7 on 2020-06-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200626_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humidityreading',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='temperaturereading',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
